export const SET_CUSTOMERS_REDUX = "SET_CUSTOMERS_REDUX";
export const CREATE_CUSTOMER_REDUX = "CREATE_CUSTOMER_REDUX";
export const UPDATE_CUSTOMER_REDUX = "UPDATE_CUSTOMER_REDUX";
export const DELETE_CUSTOMER_REDUX = "DELETE_CUSTOMER_REDUX";
